version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: api-nestjs
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: apinest
      MYSQL_USER: mysql
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
    driver: local
